version: "3.8"

services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    image: birfbkdstsbhbk/learnawareai:api
    container_name: fastapi_app
    ports:
      - "4000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: birfbkdstsbhbk/learnawareai:frontend
    container_name: nextjs_app
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
